### ISSUE TITLE
App Crashes new issue!

### ISSUE THREAD

**Issue by elblogbruno** [PavieOlivier/AndroidNotificationListener#3]
I am getting this issue right now. What can be the problem?

E/AndroidRuntime(29516): java.lang.RuntimeException: Unable to instantiate service com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/AndroidRuntime(29516): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4218)
E/AndroidRuntime(29516): 	at android.app.ActivityThread.access$200(ActivityThread.java:242)
E/AndroidRuntime(29516): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2083)
E/AndroidRuntime(29516): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(29516): 	at android.os.Looper.loop(Looper.java:228)
E/AndroidRuntime(29516): 	at android.app.ActivityThread.main(ActivityThread.java:7813)
E/AndroidRuntime(29516): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29516): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(29516): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
E/AndroidRuntime(29516): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference

**Comment by elblogbruno** [comment]
I added the example code on a separate file and in main file I created a kind of Java based fragment system as that is how I LL use it.  But before I tried the original plugin and worked in the same setup, why only switching to this one makes the app crash?

**Comment by PavieOlivier** [comment]
Hello 
Sorry for the delay,
The official plugin is working as expected, right? only this example is not working.
I am aware of this issue, but unfortunately, I cannot provide a proper support for this particular problem right now (since the official plugin is working).
I have some client work that is taking a very long time.
I can only give time to this example as soon as I finish my work. I do really apologize for the inconvenience.
Like I said, **IF** the plugin is working as expected, the example should not be big of an issue

**Comment by elblogbruno** [comment]
The thing is I need to extract more data from a notification not only the title or package name.

The original plugin does not give lot of information. Don't worry I'll investigate myself!

Thanks

**Comment by PavieOlivier** [comment]
Please by the original plugin, you mean the one of "cachet" or the one I forked and modified?

**Comment by PavieOlivier** [comment]
Please by the original plugin, 
do you mean
- the one of "cachet" : https://pub.dev/packages/notifications
- or the one I forked and modified?: https://pub.dev/packages/android_notification_listener

If you are referring to the second one, you can already extract more data than just the package name, however I need to investigate  too

**Comment by elblogbruno** [comment]
By original I mean the "cachet". I tried modifying it to get more data no success, and the one you forked and modified crashes with the error at the top.

**Comment by PavieOlivier** [comment]
I modified it and it works properly on my machine, that is why debugging it is a pain cause I don't have any error...

**Comment by elblogbruno** [comment]
E/AndroidRuntime(29516): java.lang.RuntimeException: Unable to instantiate service com.emilecode.android_notification_listener.AndroidNotificationListenerPlugin: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/AndroidRuntime(29516): at android.app.ActivityThread.handleCreateService(ActivityThread.java:4218)
E/AndroidRuntime(29516): at android.app.ActivityThread.access$200(ActivityThread.java:242)
E/AndroidRuntime(29516): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2083)
E/AndroidRuntime(29516): at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(29516): at android.os.Looper.loop(Looper.java:228)
E/AndroidRuntime(29516): at android.app.ActivityThread.main(ActivityThread.java:7813)
E/AndroidRuntime(29516): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29516): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(29516): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
E/AndroidRuntime(29516): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference

By the issue I feel it does not get any context the package. I have implemented it by the example code provided with this package .

**Comment by PavieOlivier** [comment]
Hello I just pushed an overall upgrade (**on this repo only**) and changed almost all the files.
This should work now, can you please try to fork and run the example code from here

**Comment by elblogbruno** [comment]
Now it does work!!!! Thank you a lot!

**Comment by PavieOlivier** [comment]
your welcome :) pushing an update to pub.dev :)

**Comment by elblogbruno** [comment]
Do you know If I can get if message comes from a chat like whatsapp and get every message?

**Comment by PavieOlivier** [comment]
yes you can, and to help you even further I already made a code for this  [here](https://github.com/PavieOlivier/studyBuddy).

the specific file that you have to look [into is this one](https://github.com/PavieOlivier/studyBuddy/blob/master/lib/Logic/aiNotificationLogic.dart)  (please keep in mind that I was using version 1 of my package so you will have to change your code accordingly). 

You can  [test the APK of that release ](https://drive.google.com/file/d/1cZhhWkJ9tQ-3NslSWLmR0kghN0uQIDJK/view?usp=drivesdk)

Thank you

**Comment by elblogbruno** [comment]
I meant this that I do use in java and did discover even though google's documentation is not very clear

![2020-08-20 15_10_50-MyNotificationService java - Visual Studio Code](https://user-images.githubusercontent.com/10481058/90774215-622ae800-e2f7-11ea-8853-73a1108b12ef.png)

**Comment by PavieOlivier** [comment]
please read my previous comment :)
What you are currently referring is the (extra) content of the  notification, you can get it with my package

**Comment by elblogbruno** [comment]
I edited the comment and added a photo. Eventough don't worrt thanks for all!

**Comment by PavieOlivier** [comment]
my previous comment refers you to 3 links so just check them out, please :)
You will be able to get 
- the whatsApp message
- the sender name 
- other info related to the notification

**Comment by elblogbruno** [comment]
Sorry for misunderstanding your comment! Thanks

**Comment by PavieOlivier** [comment]
no problem bro :)

**Comment by elblogbruno** [comment]
But i can't find the part of extracting the sender name

**Comment by PavieOlivier** [comment]
in [the code](https://github.com/PavieOlivier/studyBuddy/blob/master/lib/Logic/aiNotificationLogic.dart) i sent you.
there is a place 
```
 subMessageLogic.serverQueuMessage.add(event.packageMessage);
 subMessageLogic.serverQueuName.add(event.packageText);
```

this means the sender name shall be  **event.packageText** and the message shall be **event.packageMessage**

**Comment by elblogbruno** [comment]
and can I get also the notification icon?

**Comment by PavieOlivier** [comment]
> and can I get also the notification icon?

no bro, I have not found yet how to do this sorry.

by the way i just pushed another update and made an important change. can you fork this repo and try to see if it still works on your device ?

**Comment by PavieOlivier** [comment]
allo ?

**Comment by elblogbruno** [comment]
i'll check it now!

**Comment by PavieOlivier** [comment]
ok ok I am waiting then :) .
If it works i will push it to pub.dev

**Comment by elblogbruno** [comment]
```
Running Gradle task 'assembleDebug'...
e: C:\Users\elblo\AppData\Local\Pub\Cache\git\AndroidNotificationListener-8603f48e082c24d32d439e9f866c38339778cb28\android\src\main\kotlin\com\emilecode\android_notification_listener2\NotificationListener.kt: (18, 7): Redeclaration: NotificationListener
e: C:\Users\elblo\AppData\Local\Pub\Cache\git\AndroidNotificationListener-ee1218e1ff22700a1345bcfa716d1df6570d591f\android\src\main\kotlin\com\emilecode\android_notification_listener2\NotificationListener.kt: (17, 7): Redeclaration: NotificationListener

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android_notification_listener2:compileDebugKotlin'.
```

Getting this issue when building apk

**Comment by PavieOlivier** [comment]
As of jul 2020 you will get this Redeclaration error when there is an already existing class with the same name, so either you have to rename or move to a different package.

My solution is that you just delete everything in the cache 
- at C:\Users\elblo\AppData\Local\Pub\Cache\git
remove both folders << androidNotificationListener >>

**Comment by PavieOlivier** [comment]
you can also try` File -> Invalidate Caches / Restart` inside android studio

**Comment by elblogbruno** [comment]
Thanks for the solution! I can confirm the package is working!

**Comment by PavieOlivier** [comment]
Thanks brother
now finally it works 
Once I find a way to get the image I will upgrade this package
