### ISSUE TITLE
onData event with a notification is called twice

### ISSUE THREAD

**Issue by elblogbruno** [PavieOlivier/AndroidNotificationListener#4]
![error](https://user-images.githubusercontent.com/10481058/92023269-d4baaf80-ed5c-11ea-9a3b-7acf0d3e05b2.png)

As you see by the picture when onData event is called I get it twice,it can be seen on the timestamp!
Picture posted is a screenshot of the logcat.

Hope this can be fixed, I will try looking at the code. I'd like to know if I am the only one having this issue!
Thanks
Cordially

**Comment by PavieOlivier** [comment]
well bro it is pretty normal.. it is a listenable stream type......  which means that it can occur even more than twice...
the same thing would have occurred if you were listening to a scroll event on a scroll controller.
I would suggest this approach

```
YourClassName{
bool isFunctionRunning;
     initState(){
         isFunctionRunning = false;
     }
///Somewhere in your code whenever your function is called

    void myFunction(){
      if(isFunctionRunning == true)
       {return;}
      isFunctionRunning = true;
      .
      .
      .
      /// end of Rest of the code here
      isFunctionRunning = false;
  }
}
```

**Comment by PavieOlivier** [comment]
in another word, just create a bool outside of the method and mark it to true while the function is running, and exist the method every time the function is true
at the end of the function set it to false that's all

**Comment by elblogbruno** [comment]
I  don't get it, if I receive the notification once on the phone I get it more than once on flutter because of the type of stream?
So the fix is maybe to see the timestamp and check if they are the same text and only play once? I don't understand your solution sorry!
thanks
bruno

**Comment by PavieOlivier** [comment]
send me your code, here and I will add the changes for you

**Comment by PavieOlivier** [comment]
or use a website like https://www.codepile.net then send me the link and i will edit it for you

**Comment by elblogbruno** [comment]
Thank you https://www.codepile.net/pile/m5V9oAqY here you have!

**Comment by PavieOlivier** [comment]
made the change you can go and check,
Please make sure that the **getMessageAnalisis** method is a future so that we can await it otherwise it wont work

**Comment by elblogbruno** [comment]
ok thank you! I still need to learn what future functions are but it seems like they are async functions. 
Cordially
Bruno

**Comment by PavieOlivier** [comment]
just try the code :) it will work mostly work
Yeah, they are async functions :)
you can also remove this part 
```
  if(event.packageMessage != null){
            ///[Please make sure that the getMessageAnalisis method is a future and is awaiting otherwise it wont work ]
            Future<String> data = await  getMessageAnalisis(event.packageMessage);
            } 
```

If you remove it and receive a notification, in 100% of the time it will only come once 
But since you want to do some work you might want to learn more about async functions

**Comment by elblogbruno** [comment]
Thanks!
